start C:\ahk_scripts\simplicityCommander.ahk
start C:\ahk_scripts\windowsCommandLine.ahk
start C:\ahk_scripts\windowsExplorer_w10.ahk
start C:\ahk_scripts\GITkonsola.ahk
start C:\ahk_scripts\platformioCLI.ahk
start C:\ahk_scripts\paint.ahk
start C:\ahk_scripts\dane.ahk
start C:\ahk_scripts\eclipse.ahk
start C:\ahk_scripts\arrows.ahk