python -m pip install --upgrade pip
python -m pip install --upgrade beautifultable
python -m pip install --upgrade readchar
python -m pip install --upgrade colored
python -m pip install --upgrade pandas
python -m pip install --upgrade docopt
python -m pip install --upgrade clipboard
python -m pip install --upgrade auto-py-to-exe
@set /p DUMMY=Hit ENTER to continue...